import { Composition } from "remotion";
import { SubtitleVideo } from "./SubtitleVideo";
import { AutoTikTokOverlayVideo } from "./AutoTikTokOverlayVideo";
import episode001 from "./data/episode-001.json";
import episode002 from "./data/episode-002.json";
import autoGenerated from "./data/auto-generated.json";

export const RemotionVideo = () => {
  return (
    <>
      <Composition
        id="Episode001-L001"
        component={SubtitleVideo}
        durationInFrames={16200}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{ subtitles: episode001, episodeTitle: "Episode 001 · Survival Thai 01", theme: "thaiFlag" }}
      />

      <Composition
        id="Episode002-L002"
        component={SubtitleVideo}
        durationInFrames={14400}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{ subtitles: episode002, episodeTitle: "Episode 002 · Survival Thai 02" }}
      />

      <Composition
        id="AutoTikTokOverlay"
        component={AutoTikTokOverlayVideo}
        durationInFrames={autoGenerated.durationInFrames}
        fps={autoGenerated.fps}
        width={autoGenerated.width}
        height={autoGenerated.height}
        defaultProps={{
          videoSrc: autoGenerated.videoSrc,
          captions: autoGenerated.captions,
          cues: autoGenerated.cues,
        }}
      />
    </>
  );
};
