#!/usr/bin/env python3
"""Roll up unrolled creator_annotations into a per-channel prompt-feedback notes
markdown file.

Behaviour:
- Selects creator_annotations rows where rolled_up_at IS NULL, joined to their
  parent creator_eval_scripts row.
- FAILS CLOSED on prompt-SHA drift: if any unrolled row's prompt_sha doesn't
  match the current `git rev-parse HEAD:<prompt_path>`, exits 1 unless --force.
- Writes new sections to {channel}/notes/prompt-feedback-notes.md, prepended
  below the file header so newest is first.
- Idempotent: the file ends with `<!-- rolled-up-annotation-ids: ... -->`. Rows
  whose IDs are in the footer are skipped, even if their rolled_up_at got
  cleared by a re-annotation. After a successful append, the script PATCHes
  rolled_up_at on the processed rows AND updates the footer.

Usage:
    python3 scripts/aggregate_prompt_feedback.py --type course
    python3 scripts/aggregate_prompt_feedback.py --type youtube
    python3 scripts/aggregate_prompt_feedback.py --type all
    python3 scripts/aggregate_prompt_feedback.py --type course --force
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _supabase_rest import select, update  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent

NOTES_PATH = {
    "youtube": REPO_ROOT / "youtube" / "notes" / "prompt-feedback-notes.md",
    "course": REPO_ROOT / "course" / "notes" / "prompt-feedback-notes.md",
}

FOOTER_RE = re.compile(r"<!--\s*rolled-up-annotation-ids:\s*([^>]*?)\s*-->", re.DOTALL)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--type", choices=("youtube", "course", "all"), required=True)
    p.add_argument(
        "--force",
        action="store_true",
        help="proceed even if a row's prompt_sha differs from current HEAD",
    )
    return p.parse_args()


def git_sha_for_path(prompt_path: str) -> str:
    try:
        r = subprocess.run(
            ["git", "rev-parse", f"HEAD:{prompt_path}"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            timeout=10,
        )
        return r.stdout.strip() if r.returncode == 0 else ""
    except Exception:
        return ""


def read_existing(path: Path) -> Tuple[str, set]:
    if not path.exists():
        return "", set()
    text = path.read_text("utf-8")
    m = FOOTER_RE.search(text)
    if not m:
        return text, set()
    ids_csv = m.group(1).strip()
    ids = {s.strip() for s in ids_csv.split(",") if s.strip()}
    return text, ids


def build_header(channel: str) -> str:
    title = "YouTube" if channel == "youtube" else "Course"
    return (
        f"# {title} Prompt Feedback Notes\n\n"
        f"_Rolling digest of Nine's per-script annotations. Newest entries at top._\n"
        f"_Generated by scripts/aggregate_prompt_feedback.py - do not hand-edit "
        f"the rolled-up-annotation-ids footer._\n"
    )


def render_section(script: Dict, anns: List[Dict]) -> str:
    overall = next((a for a in anns if a["scope"] == "overall"), None)
    blocks = [a for a in anns if a["scope"] == "block"]
    grouped = defaultdict(list)
    for a in blocks:
        grouped[a["rating"]].append(a)

    lines: List[str] = []
    today = datetime.now(timezone.utc).date().isoformat()
    lines.append(
        f"## {today}: {script['script_id']} (eval run {script['eval_run_id']})"
    )
    lines.append("")
    sha = script.get("prompt_sha") or "(unpinned)"
    lines.append(f"Prompt SHA: `{sha}`  ")
    lines.append(f"Prompt path: `{script.get('prompt_path', '')}`")
    lines.append("")

    if overall:
        comment = overall["comment"].strip() or "(no comment)"
        lines.append(f"**Overall: {overall['rating']}.** {comment}")
        lines.append("")

    rework = grouped.get("rework", [])
    if rework:
        lines.append(f"**Rework sections ({len(rework)}):**")
        for a in sorted(rework, key=lambda r: r["block_id"] or ""):
            label = a.get("block_label") or ""
            label_str = f" ({label})" if label else ""
            comment = a["comment"].strip() or "(no comment)"
            lines.append(f"- `{a['block_id']}`{label_str}: {comment}")
        lines.append("")

    ok = grouped.get("ok", [])
    if ok:
        ok_labels = ", ".join(
            f"`{a['block_id']}`" + (f" ({a.get('block_label')})" if a.get("block_label") else "")
            for a in sorted(ok, key=lambda r: r["block_id"] or "")
        )
        lines.append(f"**Ok ({len(ok)}):** {ok_labels}")
        lines.append("")

    good = grouped.get("good", [])
    if good:
        good_labels = ", ".join(
            f"`{a['block_id']}`" + (f" ({a.get('block_label')})" if a.get("block_label") else "")
            for a in sorted(good, key=lambda r: r["block_id"] or "")
        )
        lines.append(f"**Good ({len(good)}):** {good_labels}")
        lines.append("")

    return "\n".join(lines)


def write_notes(path: Path, header: str, new_sections: List[str], all_ids: set) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing_text, _ = read_existing(path)
    existing_body = ""
    if existing_text:
        # Strip header + footer from prior text; we re-emit them fresh.
        body = FOOTER_RE.sub("", existing_text).strip()
        if body.startswith("#"):
            # Drop existing header (first markdown heading + following blank line up to next ##).
            body = re.sub(r"^# .+?(?=\n## |\Z)", "", body, count=1, flags=re.DOTALL).strip()
        existing_body = body

    parts: List[str] = [header.strip(), ""]
    for s in new_sections:
        parts.append(s.strip())
        parts.append("")
        parts.append("---")
        parts.append("")
    if existing_body:
        parts.append(existing_body.strip())
        parts.append("")

    sorted_ids = sorted(all_ids)
    parts.append(f"<!-- rolled-up-annotation-ids: {','.join(sorted_ids)} -->")
    path.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")


def aggregate_channel(channel: str, force: bool) -> int:
    notes_path = NOTES_PATH[channel]
    _, included_ids = read_existing(notes_path)

    rows = select(
        "creator_annotations",
        params={
            "select": "id,scope,block_id,block_label,rating,comment,rolled_up_at,eval_script_id,creator_eval_scripts(id,script_type,eval_run_id,script_id,prompt_path,prompt_sha)",
            "rolled_up_at": "is.null",
            "creator_eval_scripts.script_type": f"eq.{channel}",
            "order": "created_at.asc",
        },
    )
    rows = [r for r in rows if r.get("creator_eval_scripts")]
    rows = [r for r in rows if r["creator_eval_scripts"]["script_type"] == channel]
    rows = [r for r in rows if r["id"] not in included_ids]

    if not rows:
        print(f"[{channel}] no new annotations to roll up.")
        return 0

    drift_errors: List[str] = []
    by_script: Dict[str, Dict] = {}
    by_script_anns: Dict[str, List[Dict]] = defaultdict(list)
    for r in rows:
        s = r["creator_eval_scripts"]
        sid = s["id"]
        by_script[sid] = s
        by_script_anns[sid].append(r)

    for sid, s in by_script.items():
        head_sha = git_sha_for_path(s["prompt_path"])
        if not head_sha:
            print(
                f"[{channel}] WARN: cannot read git SHA for {s['prompt_path']} "
                "(prompt is not tracked? skipping drift check)",
                file=sys.stderr,
            )
            continue
        if s["prompt_sha"] and s["prompt_sha"] != head_sha:
            drift_errors.append(
                f"  - {s['script_id']} (run {s['eval_run_id']}): annotated against "
                f"{s['prompt_sha'][:8]}, current HEAD is {head_sha[:8]}"
            )

    if drift_errors and not force:
        print(
            f"[{channel}] FAIL: prompt has been edited since these annotations were taken.",
            file=sys.stderr,
        )
        for e in drift_errors:
            print(e, file=sys.stderr)
        print(
            "Re-generate the eval set against the current prompt, or pass --force to roll up anyway.",
            file=sys.stderr,
        )
        return 3

    sections: List[str] = []
    rolled_ids: List[str] = []
    for sid, script in by_script.items():
        anns = by_script_anns[sid]
        sections.append(render_section(script, anns))
        rolled_ids.extend(a["id"] for a in anns)

    new_id_set = set(rolled_ids)
    write_notes(notes_path, build_header(channel), sections, included_ids | new_id_set)

    now_iso = datetime.now(timezone.utc).isoformat()
    update(
        "creator_annotations",
        filters={"id": f"in.({','.join(rolled_ids)})"},
        patch={"rolled_up_at": now_iso},
    )
    print(f"[{channel}] appended {len(sections)} script section(s) with {len(rolled_ids)} annotation(s).")
    print(f"[{channel}] notes file: {notes_path}")
    return 0


def main() -> int:
    args = parse_args()
    channels = ("youtube", "course") if args.type == "all" else (args.type,)
    rc = 0
    for c in channels:
        rc = aggregate_channel(c, args.force) or rc
    return rc


if __name__ == "__main__":
    sys.exit(main())
